name: document-intelligence-tools

services:
  frontend-tools:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/workspace
      - /workspace/node_modules

  tools:
    build:
      context: ./backend
      target: test
    working_dir: /workspace
    environment:
      PIP_TOOLS_CACHE_DIR: /tmp/pip-tools
      MYPY_CACHE_DIR: /tmp/mypy
      RUFF_CACHE_DIR: /tmp/ruff
    volumes:
      - ./backend:/workspace
